services:
  - type: web
    name: real-time-whiteboard
    env: node
    rootDir: server          
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
